"""Improve activity logs

Revision ID: 086f1fee9137
Revises: a1e244bd30ad
Create Date: 2026-01-13 20:09:12.743116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '086f1fee9137'
down_revision = 'a1e244bd30ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('target_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('extra', sa.Text(), nullable=True))
        batch_op.alter_column('action',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['target_user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_activity_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_category'))
        batch_op.alter_column('action',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
        batch_op.drop_column('extra')
        batch_op.drop_column('target_user_id')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
