"""Change Article model

Revision ID: f822e0c68574
Revises: 086f1fee9137
Create Date: 2026-01-16 14:11:57.517775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f822e0c68574'
down_revision = '086f1fee9137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('articles_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('date_created')
        batch_op.drop_column('article_body')
        batch_op.drop_column('article_image')
        batch_op.drop_column('article_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False))
        batch_op.add_column(sa.Column('article_image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=False))
        batch_op.add_column(sa.Column('article_body', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False))
        batch_op.add_column(sa.Column('date_created', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('articles_ibfk_1'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('author_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('image')
        batch_op.drop_column('body')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
